#!/bin/bash

OUT_DIR=$1

for i in $(ls);
do
	FN=$(find $OUT_DIR -iname "$i")

	if [ "" == "$FN" ]
	then
		echo "$i MISSING"
	else
		for j in $FN;
		do

			md5found=$(md5sum $j | cut -d " " -f1)	
			md5orig=$(md5sum $i | cut -d " " -f1)

			if [ "$md5orig" == "$md5found" ]
			then
				echo "$i $md5orig vs $md5found $j OK"
			else
				echo "$i $md5orig vs $md5found $j FAIL"
			fi

		done	
	fi

	echo ""
done;