#!/bin/bash

OUT_DIR=$1

for i in $(ls);
do
	md5found=$(md5sum $(find $OUT_DIR -iname "$i") | cut -d " " -f1)	
	md5orig=$(md5sum $i | cut -d " " -f1)

	if [ "$md5orig" == "$md5found" ]
	then
		echo "$i $md5orig vs $md5found OK"
	else
		echo "$i $md5orig vs $md5found FAIL"
	fi

done;